sudo: false
language: scala
scala:
   - 2.12.2
jdk:
  - oraclejdk8

env: COVERALLS_REPO_TOKEN="25Jpp3rstmYvc8pbskcjxGblhma8mMLB0"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport &&
        sbt coverageAggregate
after_success:
  - sbt coveralls
